#!/bin/sh
# Launch wrapper for Xonotic Touch (Flatpak, Click, local packages).
set -e

APP_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
export XONOTIC_TOUCH_APP_ROOT="$APP_ROOT"
BUNDLE_DATA="${APP_ROOT}/data"
BIN="${APP_ROOT}/bin/xonotic"
SCREEN_CALC="${APP_ROOT}/share/xonotic/screen-calc.sh"
FETCH_ASSETS="${APP_ROOT}/share/xonotic/fetch-assets-runtime.sh"
SYNC_BUNDLE="${APP_ROOT}/share/xonotic/sync-bundle-data.sh"
USER_BASE="${XDG_DATA_HOME:-${HOME}/.local/share}/xonotic-touch"
USER_DATA="${USER_BASE}/data"
LAYOUT_CFG="${USER_DATA}/screen.layout.cfg"
TOUCH_PROFILE="${XONOTIC_TOUCH_PROFILE:-standard}"
TOUCH_PERF_PROFILE="${XONOTIC_TOUCH_PERF_PROFILE:-balanced}"
TOUCH_PROFILES_DIR="${USER_DATA}/touch/profiles"
USER_TOUCH_LAYOUT="${XONOTIC_TOUCH_LAYOUT:-${HOME}/.xonotic/touch.layout.cfg}"

if [ ! -x "$BIN" ]; then
    echo "xonotic-touch: engine binary not found at $BIN" >&2
    exit 1
fi

mkdir -p "$USER_DATA"

if [ -x "$SYNC_BUNDLE" ]; then
    "$SYNC_BUNDLE" "$BUNDLE_DATA" "$USER_DATA"
fi

if [ -x "$FETCH_ASSETS" ]; then
    XONOTIC_TOUCH_DATA_DIR="$USER_DATA" "$FETCH_ASSETS" "$USER_DATA"
elif [ -f "$APP_ROOT/share/xonotic/fetch-assets-runtime.sh" ]; then
    sh "$APP_ROOT/share/xonotic/fetch-assets-runtime.sh" "$USER_DATA"
fi

DATA_DIR="$USER_DATA"

# Detect desktop environment vs confined mobile (Ubuntu Touch Mir has no DISPLAY/WAYLAND).
if [ -n "${DISPLAY:-}" ] || [ -n "${WAYLAND_DISPLAY:-}" ]; then
    IS_DESKTOP=1
else
    IS_DESKTOP=0
fi

if [ "$IS_DESKTOP" = "1" ]; then
    FULLSCREEN=0
    XONOTIC_VID_WIDTH="${XONOTIC_DESKTOP_WIDTH:-412}"
    XONOTIC_VID_HEIGHT="${XONOTIC_DESKTOP_HEIGHT:-915}"
    XONOTIC_TOUCH_XDPI="${XONOTIC_TOUCH_XDPI:-429}"
    XONOTIC_TOUCH_YDPI="${XONOTIC_TOUCH_YDPI:-429}"
    XONOTIC_TOUCH_DENSITY="${XONOTIC_TOUCH_DENSITY:-2.625}"
    cat > "$LAYOUT_CFG" <<EOF
// Generated by packaging/start.sh (desktop portrait test window)
vid_width ${XONOTIC_VID_WIDTH}
vid_height ${XONOTIC_VID_HEIGHT}
vid_conwidthauto 0
vid_conwidth ${XONOTIC_VID_WIDTH}
vid_conheight ${XONOTIC_VID_HEIGHT}
vid_touchscreen_xdpi ${XONOTIC_TOUCH_XDPI}
vid_touchscreen_ydpi ${XONOTIC_TOUCH_YDPI}
vid_touchscreen_density ${XONOTIC_TOUCH_DENSITY}
EOF
elif [ -f "$SCREEN_CALC" ]; then
    # shellcheck source=/dev/null
    . "$SCREEN_CALC"
    xonotic_screen_calc "$LAYOUT_CFG"
else
    echo "xonotic-touch: screen-calc missing at $SCREEN_CALC" >&2
    XONOTIC_VID_WIDTH="${XONOTIC_DEFAULT_WIDTH:-1920}"
    XONOTIC_VID_HEIGHT="${XONOTIC_DEFAULT_HEIGHT:-1080}"
    XONOTIC_TOUCH_XDPI="${XONOTIC_TOUCH_XDPI:-320}"
    XONOTIC_TOUCH_YDPI="${XONOTIC_TOUCH_YDPI:-320}"
    XONOTIC_TOUCH_DENSITY="${XONOTIC_TOUCH_DENSITY:-2.0}"
    cat > "$LAYOUT_CFG" <<EOF
// Fallback layout (screen-calc.sh not installed)
vid_width ${XONOTIC_VID_WIDTH}
vid_height ${XONOTIC_VID_HEIGHT}
vid_touchscreen_xdpi ${XONOTIC_TOUCH_XDPI}
vid_touchscreen_ydpi ${XONOTIC_TOUCH_YDPI}
vid_touchscreen_density ${XONOTIC_TOUCH_DENSITY}
EOF
fi

if [ -n "${LD_LIBRARY_PATH:-}" ]; then
    export LD_LIBRARY_PATH="${APP_ROOT}/lib:${LD_LIBRARY_PATH}"
else
    export LD_LIBRARY_PATH="${APP_ROOT}/lib"
fi

XONOTIC_LOCK="${HOME}/.xonotic/lock"
if [ -f "$XONOTIC_LOCK" ]; then
    rm -f "$XONOTIC_LOCK"
fi

if [ "$IS_DESKTOP" != "1" ]; then
    FULLSCREEN=1
fi

STARTUP_CFG="${DATA_DIR}/touch/startup.cfg"
mkdir -p "${DATA_DIR}/touch/profiles"
{
    echo "// Generated by packaging/start.sh"
    if [ -f "${TOUCH_PROFILES_DIR}/${TOUCH_PROFILE}.cfg" ]; then
        echo "exec touch/profiles/${TOUCH_PROFILE}.cfg"
    else
        echo "xonotic-touch: touch profile missing: ${TOUCH_PROFILES_DIR}/${TOUCH_PROFILE}.cfg" >&2
    fi
    if [ -f "${TOUCH_PROFILES_DIR}/${TOUCH_PERF_PROFILE}.cfg" ]; then
        echo "exec touch/profiles/${TOUCH_PERF_PROFILE}.cfg"
    fi
    if [ -f "$USER_TOUCH_LAYOUT" ]; then
        echo "exec ${USER_TOUCH_LAYOUT}"
    fi
} > "$STARTUP_CFG"

cd "$USER_BASE"

# shellcheck disable=SC2086
exec "$BIN" -xonotic \
    +exec xonotic.cfg \
    +exec screen.layout.cfg \
    +vid_fullscreen "$FULLSCREEN" \
    +vid_touchscreen 1 \
    +vid_conwidthauto 0 \
    +vid_conwidth "$XONOTIC_VID_WIDTH" \
    +vid_conheight "$XONOTIC_VID_HEIGHT" \
    +vid_width "$XONOTIC_VID_WIDTH" \
    +vid_height "$XONOTIC_VID_HEIGHT" \
    +vid_touchscreen_xdpi "$XONOTIC_TOUCH_XDPI" \
    +vid_touchscreen_ydpi "$XONOTIC_TOUCH_YDPI" \
    +vid_touchscreen_density "$XONOTIC_TOUCH_DENSITY" \
    +cl_movement 1 \
    +con_closeontoggle 1 \
    +scr_screenshot_jpeg 0
